### ISSUE TITLE
What is the origin of a body with fixtures?

### ISSUE THREAD

**Issue by clankill3r** [piqnt/planck.js#97]
I'm trying to create a logo using planck.js. The idea is to create a SVG based on the state of the physics.

I'm pretty far but I can't figure out what is going on with the positions.

Those boxes:
![Screen Shot 2019-07-16 at 14 42 25](https://user-images.githubusercontent.com/738650/62687430-0ed54880-b9c7-11e9-83f1-8899fb0b0976.png)

Should match in some way this:
![Screen Shot 2019-07-16 at 14 47 28](https://user-images.githubusercontent.com/738650/62687416-0846d100-b9c7-11e9-8e9e-3624f38e7f21.png)

It only looks correct at the animation start.

I made a codepen
https://codepen.io/clankill3r/pen/bXvvaP

Hope you can have a look.

**Comment by zOadT** [comment]
I might figured it out, here is the relevant code:
```
vecs_A_0 = rescale_offset_and_make_vec2(vecs_A_0, scale, -97, 377 - 88);
vecs_A_1 = rescale_offset_and_make_vec2(vecs_A_1, scale, -97, 377 - 88);
vecs_A_2 = rescale_offset_and_make_vec2(vecs_A_2, scale, -97, 377 - 88);
vecs_P_0 = rescale_offset_and_make_vec2(vecs_P_0, scale, -214, 377 - 88);
vecs_P_1 = rescale_offset_and_make_vec2(vecs_P_1, scale, -214, 377 - 88);
vecs_R_0 = rescale_offset_and_make_vec2(vecs_R_0, scale, -328, 377 - 88);
vecs_R_1 = rescale_offset_and_make_vec2(vecs_R_1, scale, -328, 377 - 88);
vecs_R_2 = rescale_offset_and_make_vec2(vecs_R_2, scale, -328, 377 - 88);
vecs_I_0 = rescale_offset_and_make_vec2(vecs_I_0, scale, -410, 377 - 88);


function create_body(name, vecs_arrays, pos) {

    var body = world.createBody({
        position : pos,
        type : 'dynamic',
        allowSleep : false
    });

    body.name = name;

    for (var i = 0; i < vecs_arrays.length; i++) {
        var vecs = vecs_arrays[i];
        body.createFixture(pl.Polygon(vecs), 2.0); // what is 2.0?
    }

    return body;
}



body_A_0 = create_body("A_0", [vecs_A_0, vecs_A_1, vecs_A_2], Vec2(-r + 0.1633 * (r+r), 2*88*scale));
body_P   = create_body("P", [vecs_P_0, vecs_P_1],             Vec2(-r + 0.3603 * (r+r), 2*88*scale));
body_R   = create_body("R", [vecs_R_0, vecs_R_1, vecs_R_2],   Vec2(-r + 0.5526 * (r+r), 2*88*scale));
body_I   = create_body("I", [vecs_I_0],                       Vec2(-r + 0.6904 * (r+r), 2*88*scale));
body_A_1 = create_body("A_1", [vecs_A_0, vecs_A_1, vecs_A_2], Vec2(-r + 0.8407 * (r+r), 2*88*scale));

// . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

testbed.step = function() {

    update_apria_svg_logos();

};


function dbg_test(body, color, width, height) {

    var x = map(body.getPosition().x, -15, 15, 0, 100);
    var y = map(body.getPosition().y-2*88*scale, -15, 15, 100, 0);

    var a = -body.getAngle() * R2D;

    var hx = width/2;
    var hy = height/2;

    d3.selectAll(".apria_logo")
    .append("rect")
    .attr("x", 0)
    .attr("y", 0)
    .attr("width", width)
    .attr("height", height)
    .attr("style", "fill:"+color)
    .attr("transform", "translate("+x+", "+y+") rotate("+a+", "+hx+", "+hy+")")
    ;

}
```
So I basically changed the offset parameter to `377 - 88`, so the shapes are centered around the origin, and changed `hx` and `hy`, so that the rect is rotated around its center.

Let me know if it works.

**Comment by zOadT** [comment]
BTW: You duplicated the coordinates in your vecs array. I think
```
vecs_A_0 = [116, 201, 148, 377, 119, 377, 113, 338, 116, 201];
[...]
```
should also work.

**Comment by shakiba** [comment]
Is the problem solved?
By the way, this is so cool! :)

**Comment by shakiba** [comment]
I just published a small change to make it possible to change testebed y-axis direction and match it with svg coordinate. From v0.3.9 you can set `testbed.scaleY *= -1` and it will reverse y direction. Here is same code (with zOadT's changes) and reversed y-axis (please note gravity is positive now):
https://codepen.io/piqnt/pen/GVYMLK

**Comment by clankill3r** [comment]
Sorry for the late reply, I was on vacation.

@zOadT  @shakiba 

The problem is still there, It is better but after a while when things rotated more you can see the issues:

<img width="219" alt="Screen Shot 2019-08-29 at 18 58 21" src="https://user-images.githubusercontent.com/738650/63960865-bd811c00-ca8f-11e9-929b-61eeebab68ed.png">

<img width="172" alt="Screen Shot 2019-08-29 at 18 58 19" src="https://user-images.githubusercontent.com/738650/63960871-c1ad3980-ca8f-11e9-8c99-3c37ff676fed.png">

I made a new codepen (using version 0.39) where I remade a lot of things.
I wanted to understand the problem and not eyeball a fix.

One of the things I don't get is why they get outside the circle:

<img width="630" alt="Screen Shot 2019-08-29 at 19 07 51" src="https://user-images.githubusercontent.com/738650/63961153-5f086d80-ca90-11e9-8dbe-c1bc54529c7e.png">

I map the position using the following:
```java
var x = map(_c.body.getPosition().x, -r , r, 0, 100);
var y = map(_c.body.getPosition().y, -r , r, 0, 100);
```

Can it be that `getPosition` is influenced by the rotation?

https://codepen.io/clankill3r/pen/jONwvdY

**Comment by clankill3r** [comment]
I can not wrap my head around it, those 2 images are from the same run without changing the code:

<img width="234" alt="Screen Shot 2019-08-29 at 19 40 06" src="https://user-images.githubusercontent.com/738650/63963257-eeb01b00-ca94-11e9-8e23-dde766954625.png">

<img width="247" alt="Screen Shot 2019-08-29 at 19 39 00" src="https://user-images.githubusercontent.com/738650/63963267-f374cf00-ca94-11e9-9eaa-7db9adf6d4e0.png">

Is this a bug in planck?

**Comment by shakiba** [comment]
Cool! Your hint was actually very helpful, the problem was reusing `y` variable, here is [the fix](https://codepen.io/piqnt/pen/dybRxOa).

**Comment by shakiba** [comment]
I randomized boxes' location, probably you want to remove that!
